console/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name='console'
urlpatterns = [
    path('', views.ConsoleIndexPageView.as_view(), name='index'),
    path('login', views.ConsoleLoginPageView.as_view(), name='login'),
    path('logout', views.ConsoleLogoutRedirect.as_view(), name='logout'),
    path('forgot-password', views.ResetPasswordView.as_view(), name='forgot-password'),
    path('forgot-password-confirm/<uidb64>/<token>', views.ResetPasswordConfirmView.as_view(), name='forgot-password-confirm'),
    path('forgcot-password-complete', views.ResetPasswordCompleteView.as_view(), name='forgot-password-complete'),


    # Merchants
    path('merchants', views.MerchantsListPageView.as_view(), name='merchants'),
    path('merchants/download_csv', views.MerchantCSVDownloadView.as_view(), name='merchant-download'),
    path('merchants/<int:merchant_id>', views.MerchantDetailsPageView.as_view(), name='merchant-detail'),
    path('merchants/<int:merchant_id>/accept', views.MerchantActionAcceptedRedirect.as_view(), name='merchant-accept'),
    path('merchants/<int:merchant_id>/payment', views.MerchantActionRequestPaymentRedirect.as_view(),  name='merchant-payment'),
    path('merchants/<int:merchant_id>/confirm', views.MerchantActionPaymentConfirmedRedirect.as_view(), name='merchant-confirm'),
    path('merchants/<int:merchant_id>/register', views.MerchantActionRegistrationReminderRedirect.as_view(), name='merchant-reg-remind'),
    path('merchants/<int:merchant_id>/waitlist', views.MerchantActionWaitlistRedirect.as_view(), name='merchant-waitlist'),
    path('merchants/<int:merchant_id>/delete', views.MerchantActionDeleteRedirect.as_view(), name='merchant-delete'),
    path('merchants/<int:merchant_id>/assign', views.MerchantActionAssignPageView.as_view(), name='merchant-assign'),

    # Panels
    path('panels', views.PanelsListPageView.as_view(), name='panels'),
    path('panels/<int:panel_id>', views.PanelDetailsPageView.as_view(), name='panel-detail'),
    path('panels/<int:panel_id>/accept', views.PanelActionAcceptRedirect.as_view(), name='panel-accept'),
    path('panels/<int:panel_id>/waitlist', views.PanelActionWaitlistRedirect.as_view(), name='panel-waitlist'),
    path('panels/<int:panel_id>/deny', views.PanelActionDenyRedirect.as_view(), name='panel-deny'),
    path('panels/<int:panel_id>/delete', views.PanelActionDeleteRedirect.as_view(), name='panel-delete'),
    path('panels/schedule', views.PanelSchedulePageView.as_view(), name='panels-schedule'),
    path('panels/schedule/<int:panel_id>/assign', views.PanelActionAssignPageView.as_view(), name='panel-assign'),
    path('panels/schedule/<int:panel_id>/unassign', views.PanelActionUnscheduleRedirect.as_view(), name='panel-unassign'),
    path('panels/schedule/<int:panel_id>/cancel', views.PanelActionCancelRedirect.as_view(), name='panel-cancel'),

    # Volunteers
    path('volunteers', views.VolunteerListPageView.as_view(), name='volunteers'),
    path('volunteers/download_csv', views.VolunteerCSVDownloadView.as_view(), name='volunteer-download'),
    path('volunteers/<int:volunteer_id>', views.VolunteerDetailsPageView.as_view(), name='volunteer-detail'),
    path('volunteers/<int:volunteer_id>/accept', views.VolunteerActionAcceptRedirect.as_view(), name='volunteer-accept'),
    path('volunteers/<int:volunteer_id>/decline', views.VolunteerActionDeclinedRedirect.as_view(), name='volunteer-decline'),
    path('volunteers/<int:volunteer_id>/delete', views.VolunteerActionDeleteRedirect.as_view(), name='volunteer-delete'),
    path('volunteers/<int:volunteer_id>/task', views.VolunteerAddTaskPageView.as_view(), name='volunteer-add-task'),
    path('volunteers/<int:volunteer_id>/task/<int:task_id>/edit', views.VolunteerEditTaskPageView.as_view(), name="volunteer-edit-task"),
    path('volunteers/<int:volunteer_id>/task/<int:task_id>/delete', views.VolunteerActionDeleteTaskRedirect.as_view(), name="volunteer-delete-task"),
    path('volunteers/dashboard', views.VolunteerDashboardPageView.as_view(), name="volunteer-dashboard"),
    path('volunteers/dashboard/task/<int:volunteer_id>/start', views.VolunteerStartTaskRedirect.as_view(), name='volunteer-task-start'),
    path('volunteers/dashboard/task/<int:task_id>/end', views.VolunteerEndTaskRedirect.as_view(), name='volunteer-task-end'),
    path('volunteers/email', views.VolunteerComposeMassEmailPageView.as_view(), name='volunteer-email'),

    # Performers
    path('performers', views.PerformersListPageView.as_view(), name='performers'),
    path('performers/<int:performer_id>', views.PerformerDetailPageView.as_view(), name='performer-detail'),
    path('performers/<int:performer_id>/accept', views.PerformerActionAcceptRedirect.as_view(), name='performer-accept'),
    path('performers/<int:performer_id>/waitlist', views.PerformerActionWaitlistRedirect.as_view(), name='performer-waitlist'),
    path('performers/<int:performer_id>/decline', views.PerformerActionDeclineRedirect.as_view(), name='performer-decline'),
    path('performers/<int:performer_id>/delete', views.PerformerActionDeleteRedirect.as_view(), name='performer-delete'),
    path('performers/schedule', views.PerformersSchedulePageView.as_view(), name='performer-schedule'),
    path('performers/schedule/<int:performer_id>/assign', views.PerformerActionAssignPageView.as_view(), name='performer-assign'),
    path('performers/schedule/<int:performer_id>/unassign', views.PerformerActionUnscheduleRedirect.as_view(), name='performer-unassign'),

    # Party Hosts
    path('hosts', views.PartyHostListPageViewView.as_view(), name='hosts'),
    path('hosts/<int:host_id>', views.PartyHostDetailPageView.as_view(), name='host-detail'),
    path('hosts/<int:host_id>/accept', views.PartyHostActionAcceptRedirect.as_view(), name='host-accept'),
    path('hosts/<int:host_id>/assign', views.PartyHostActionAssignPageView.as_view(), name='host-assign'),
    path('hosts/<int:host_id>/waitlist', views.PartyHostActionWaitlistRedirect.as_view(), name='host-waitlist'),
    path('hosts/<int:host_id>/decline', views.PartyHostActionDeclineRedirect.as_view(), name='host-decline'),
    path('hosts/<int:host_id>/delete', views.PartyHostActionDeleteRedirect.as_view(), name='host-delete'),

    # Competitors
    path('competitors', views.CompetitorsListPageView.as_view(), name='competitors'),
    path('competitors/<int:competitor_id>', views.CompetitorDetailPageView.as_view(), name='competitor-detail'),
    path('competitors/<int:competitor_id>/accept', views.CompetitorActionAcceptRedirect.as_view(), name='competitor-accept'),
    path('competitors/<int:competitor_id>/decline', views.CompetitorActionDeclineRedirect.as_view(), name='competitor-decline'),
    path('competitors/<int:competitor_id>/delete', views.CompetitorActionDeleteRedirect.as_view(), name='competitor-delete')
]

paw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('console/', include('console.urls')),
    path('merchants/', include('merchants.urls')),
    path('panels/', include('panels.urls')),
    path('performers/', include('performers.urls')),
    path('volunteers/', include('volunteers.urls')),
    path('partyfloor/', include('partyfloor.urls')),
    path('dancecomp/', include('dancecomp.urls'))
]

merchants/models.py
from core.models import Event
from django.db import models

# Create your models here.
class MerchantState(models.TextChoices):
    STATE_NEW = "STATE_NEW", "New",
    STATE_ACCEPTED = "STATE_ACCEPTED", "Accepted"
    STATE_PAYMENT = "STATE_PAYMENT", "Payment Requested"
    STATE_CONFIRMED = "STATE_CONFIRMED", "Payment Confirmed"
    STATE_ASSIGNED = "STATE_ASSIGNED", "Table Assigned"
    STATE_WAITLISTED = "STATE_WAITLISTED", "Waitlisted"
    STATE_DENIED = "STATE_DENIED", "Denied"
    STATE_DELETED = "STATE_DELETED", "Deleted"
    STATE_OLD = "STATE_OLD", "Migrated Data"

class Table(models.Model):
    key = models.CharField(max_length=4, primary_key=True)
    name = models.CharField(max_length=20)
    order = models.IntegerField(default=0)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Merchant(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    email = models.CharField(max_length=100)
    legal_name = models.CharField(max_length=200)
    fan_name = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=15)
    table_size = models.ForeignKey(Table, on_delete=models.SET_NULL, null=True)
    business_name = models.CharField(max_length=200)
    wares_description = models.TextField('Description of Wares')
    underpaw_interest = models.BooleanField("Interested in underPAW", default=False, help_text="underPAW is PAWCon's Night Market. You Can find information <a href=\"https://pacanthro.org/underpaw\">here</a>")
    helper_legal_name = models.CharField(max_length=200, blank=True)
    helper_fan_name = models.CharField(max_length=200, blank=True)
    special_requests = models.TextField(blank=True)
    table_number = models.IntegerField(null=True, blank=True)
    merchant_state = models.CharField(max_length=20, choices=MerchantState, default=MerchantState.STATE_NEW, null=False)
    state_changed = models.DateField(auto_now_add=True)

    def __str__(self):
        return "{} ({})".format(self.legal_name, self.business_name)

panels/models.py
from core.models import ApplicationState, Event, DaysAvailable, EventRoom
from django.db import models

# Create your models here.
class PanelDuration(models.Model):
    key = models.CharField(max_length=4, primary_key=True)
    name = models.CharField(max_length=20)
    order = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class PanelSlot(models.Model):
    key = models.CharField(max_length=4, primary_key=True)
    name = models.CharField(max_length=30)
    order = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Panel(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    email = models.CharField(max_length=100)
    legal_name = models.CharField(max_length=200)
    fan_name = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=15)
    twitter_handle = models.CharField('Twitter/BSky Handle', max_length=30)
    telegram_handle = models.CharField(max_length=30)
    panelist_bio = models.TextField('Panelist Bio')
    panel_name = models.CharField(max_length=100)
    panel_description = models.TextField()
    panel_duration = models.ForeignKey(PanelDuration, on_delete=models.SET_NULL, null=True)
    equipment_needs = models.TextField()
    mature_content = models.BooleanField('Does your panel contain mature content?')
    panel_day = models.ManyToManyField(DaysAvailable)
    panel_times = models.ManyToManyField(PanelSlot)
    check_ids = models.BooleanField("I Agree to check ID's")
    panel_state = models.CharField(max_length=20, null=False, choices=ApplicationState, default=ApplicationState.STATE_NEW)
    state_changed = models.DateField(auto_now_add=True)
    scheduled_room = models.ForeignKey(EventRoom, on_delete=models.CASCADE, blank=True, null=True)
    scheduled_day = models.ForeignKey(DaysAvailable, on_delete=models.CASCADE, blank=True, null=True, related_name="scheduled_day")
    scheduled_time = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return "{} ({})".format(self.panel_name, self.legal_name)

partyfloor/models.py
from core.models import ApplicationState, DaysAvailable, Event
from django.db import models
from django.utils import timezone

# Create your models here.
class PartyHost(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    email = models.CharField(max_length=100)
    legal_name = models.CharField(max_length=200)
    fan_name = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=15)
    twitter_handle = models.CharField('Twitter/BSky Handle', max_length=30, null=True)
    telegram_handle = models.CharField(max_length=30, null=True)
    rbs_certification = models.CharField('RBS Certification', max_length=50, null=True)
    hotel_primary = models.CharField('Primary Name On Hotel Reservation', max_length=200)
    hotel_ack_num = models.CharField('Hotel Reservation Number', max_length=50, unique=True)
    party_days = models.ManyToManyField(DaysAvailable)
    party_name = models.CharField(help_text='The name of your party for our website.', max_length=100, null=True)
    party_description = models.TextField(help_text='A description of your party for our website.', null=True)
    ack_no_smoking = models.BooleanField('No Smoking of any kind -inside- the room or on the balcony (this includes vapes)', default=False)
    ack_amplified_sound = models.BooleanField('Amplified sound is not allowed on the balcony (inside rooms at reasonable levels is acceptable).', default=False)
    ack_verify_age = models.BooleanField('You must check ID\'s before handing out wristbands.', default=False)
    ack_wristbands = models.BooleanField('Only guests with wristbands indicating drinking age may have alcohol', default=False)
    ack_closure_time = models.BooleanField('The party floor closes to the public at 2AM, and normal hotel rules come into effect.', default=False)
    ack_suspension_policy = models.BooleanField('Failure to bide by Con Staff/Hotel Security requests will result in party suspension (zero tolerance).', default=False)
    room_number = models.IntegerField(null=True, blank=True)
    host_state = models.CharField(max_length=20, choices=ApplicationState, default=ApplicationState.STATE_NEW)
    state_changed = models.DateField(auto_now_add=True)

performers/models.py
from core.models import ApplicationState, DaysAvailable, Event
from django.db import models

# Create your models here.
class Performer(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    email = models.CharField(max_length=100)
    legal_name = models.CharField(max_length=200)
    fan_name = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=15)
    twitter_handle = models.CharField('Twitter/BSky Handle', max_length=30)
    telegram_handle = models.CharField(max_length=30)
    biography = models.TextField()
    dj_history = models.TextField()
    set_link = models.URLField(help_text="Please provide a link to a set of music from your SoundCloud or other similar service (DropBox, Box, YouTube, etc). It should be at least 30 mins in length and showcase your unique style.")
    performer_state = models.CharField(max_length=20, choices=ApplicationState, default=ApplicationState.STATE_NEW)
    state_changed = models.DateField(auto_now_add=True)
    scheduled_day = models.ForeignKey(DaysAvailable, on_delete=models.CASCADE, blank=True, null=True)
    scheduled_time = models.DateTimeField(blank=True, null=True)

console/forms/authentication.py
from crispy_forms.helper import FormHelper
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(AuthenticationForm, *args, **kwargs)

        # Crispy
        self.helper = FormHelper()
        self.helper.label_class = 'text-capitalize'

console/forms/merchants.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Fieldset, HTML, Layout, Submit
from django import forms

from merchants.models import Merchant

class MerchantAssignTableForm(forms.ModelForm):
    class Meta:
        model = Merchant
        fields = (
            'table_number',
        )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Crispy
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-sm-2 text-capitalize'
        self.helper.field_class = 'col-sm-4'
        self.helper.layout = Layout(
            Fieldset(
                'Table Info',
                HTML('<div class="row"><div class="col-sm-2">Merchant Name:</div><div class="col-sm-4">' + self.instance.business_name + '</div></div>'),
                'table_number'
            )
        )
        self.helper.add_input(Submit('submit', 'Apply', css_class='float-end'))

console/views/page_view.py
from core.models import get_current_event
from django.conf import settings
from django.views.generic.base import TemplateView

class PageView(TemplateView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        event = get_current_event()
        context['is_console'] = True
        context['event'] = event
        context['registration_search_base'] = settings.REGISTRATION_SEARCH_BASE
        context['registration_platform'] = settings.REGISTRATION_PLATFORM

        if (user.is_superuser):
            context['is_superuser'] = True
        else:
            context['has_merchant_permission'] = user.has_perm('merchants.view_merchant')
            context['has_panels_permission'] = user.has_perm('panels.view_panel')
            context['has_volunteers_permission'] = user.has_perm('volunteers.view_volunteer')
            context['has_performer_permission'] = user.has_perm('performers.view_performer')
            context['has_partyhost_permission'] = user.has_perm('partyfloor.view_partyhost')
            context['has_competitor_permission'] = user.has_perm('competitor.view_competitor')

        
        return context

console/templates/console-merchants-assign.html
{% extends 'console.html' %}
{% load crispy_forms_tags %}

{% block title %}PAWCon Apply Console - Merchants{% endblock %}

{% block tool %}
<h1>Merchant DetailsDetails</h1>
<form action="{% url 'console:merchant-assign' merchant.id %}" method="post">
	{% crispy form %}
</form>
{% endblock %}

console/templates/console-merchants-detail.html
{% extends 'console.html' %}

{% block title %}PAWCon Apply Console - Merchants{% endblock %}

{% block tool %}
<h1>Merchant Details</h1>
<table class="table">
    <tr>
        <td>Business Name:</td>
        <td>{{merchant.business_name}}</td>
    </tr>
    <tr>
        <td>Email:</td>
        <td>
            <a href="mailto:{{merchant.email}}"><i class="far fa-envelope"></i>{{merchant.email}}</a>
        </td>
    </tr>
    <tr>
        <td>Legal Name:</td>
        <td>{{merchant.legal_name}}</td>
    </tr>
    <tr>
        <td>Fan Name:</td>
        <td>{{merchant.fan_name}}</td>
    </tr>
    <tr>
        <td>Phone Number:</td>
        <td>
            <a href="tel:{{merchant.phon_number}}"><i class="fas fa-phone"></i>{{merchant.phone_number}}</a>
        </td>
    </tr>
    <tr>
        <td>Table Size:</td>
        <td>{{merchant.table_size.name}}</td>
    </tr>
    <tr>
        <td>Interested In underPAW:</td>
        <td>{{merchant.underpaw_interest}}</td>
    </tr>
    <tr>
        <td>Description of Wares:</td>
        <td>{{merchant.wares_description}}</td>
    </tr>
    <tr>
        <td>Helper Legal Name:</td>
        <td>{{merchant.helper_legal_name}}</td>
    </tr>
    <tr>
        <td>Helper Fan Name:</td>
        <td>{{merchant.helper_fan_name}}</td>
    </tr>
    <tr>
        <td>Special Requests:</td>
        <td>{{merchant.special_requests}}</td>
    </tr>
    <tr>
        <td>State:</td>
        <td>{{merchant.get_merchant_state_display}} ({{merchant.state_changed}})</td>
    </tr>
    {% if merchant.merchant_state == 'STATE_ASSIGNED' %}
    <tr>
        <td>Assigned Table:</td>
        <td>{{merchant.table_number}}</td>
    </tr>
    {% endif %}
</table>
<div>
    <h2>Actions</h2>
    {% if merchant.merchant_state == 'STATE_NEW' or merchant.merchant_state == 'STATE_WAITLISTED' %}
    <a href="{% url 'console:merchant-accept' merchant.id %}" class="btn btn-primary">Accept</a>
    {% endif %}
    {% if merchant.merchant_state == 'STATE_NEW' %}
    <a href="{% url 'console:merchant-waitlist' merchant.id %}" class="btn btn-primary">Waitlist</a>
    {% endif %}
    {% if merchant.merchant_state == 'STATE_ACCEPTED' %}
    <a href="{% url 'console:merchant-payment' merchant.id %}" class="btn btn-primary">Request Payment</a>
    <a href="{% url 'console:merchant-reg-remind' merchant.id %}" class="btn btn-primary">Remind To Register</a>
    {% endif %}
    {% if merchant.merchant_state == 'STATE_PAYMENT' %}
    <a href="{% url 'console:merchant-confirm' merchant.id %}" class="btn btn-primary">Send Confirmation</a>
    <a href="{% url 'console:merchant-payment' merchant.id %}" class="btn btn-secondary">Re-Request Payment</a> 
    {% endif %}
    {% if merchant.merchant_state == 'STATE_CONFIRMED' %}
    <a href="{% url 'console:merchant-assign' merchant.id %}" class="btn btn-primary">Assign Table</a>
    {% endif %}
    <a href="{% url 'console:merchant-delete' merchant.id %}" class="btn btn-danger">Delete Merchant</a>
</div>
<div>
    <h2>Registration</h2>
    <a href="{{registration_search_base}}{{merchant.email|urlencode}}" target="_blank" class="btn btn-outline-primary">{{registration_platform}} Lookup</a>
    <a href="{{registration_search_base}}{{merchant.legal_name|urlencode}}" target="_blank" class="btn btn-outline-primary">{{registration_platform}} Lookup (Name)</a>
    <a href={{registration_search_base}}{{merchant.helper_fan_name|urlencode}}" target="_blank" class="btn btn-outline-secondary">Helper {{registration_platform}} Lookup</a>
</div>
{% endblock %}

{% block javascript %}
{% endblock %}

console/templates/console-panels-assign.html
{% extends 'console.html' %}
{% load crispy_forms_tags %}

{% block title %}PAWCon Apply Console - Panels{% endblock %}

{% block tool %}
<h1>Panel Schedule</h1>
<div class="col-md-6">
    <form action="{% url 'console:panel-assign' panel.id %}" method="post" class="form">
        {% crispy form %}
        <input type="submit" value="Save" class="btn btn-primary">
    </form>
</div>
{% endblock %}

console/templates/console-panels-detail.html
{% extends 'console.html' %}

{% block title %}PAWCon Apply Console - Panels{% endblock %}

{% block tool %}
<h1>Panels</h1>
<div class="col-4">
    <table class="table">
        <tr>
            <td>Panel Name:</td>
            <td>{{panel.panel_name}}</td>
        </tr>
        <tr>
            <td>Fan Name:</td>
            <td>{{panel.fan_name}}</td>
        </tr>
        <tr>
            <td>Legal Name:</td>
            <td>{{panel.legal_name}}</td>
        </tr>
        <tr>
            <td>Email:</td>
            <td>{{panel.email}}</td>
        </tr>
        <tr>
            <td>Phone Number:</td>
            <td>{{panel.phone_number}}</td>
        </tr>
        <tr>
            <td>Twitter Handle:</td>
            <td>{{panel.twitter_handle}}</td>
        </tr>
        <tr>
            <td>Telegram Handle:</td>
            <td>
                <a href="https://t.me/{{panel.telegram_handle}}"><i class="fab fa-telegram"></i>
                    {{panel.telegram_handle}}</a>
            </td>
        </tr>
        <tr>
            <td>Panelist Bio:</td>
            <td>{{panel.panelist_bio}}</td>
        </tr>
        <tr>
            <td>Panel Description:</td>
            <td>{{panel.panel_description}}</td>
        </tr>
        <tr>
            <td>Panel Duration:</td>
            <td>{{panel.panel_duration.name}}</td>
        </tr>
        <tr>
            <td>Equipment Needs:</td>
            <td>{{panel.equipment_needs}}</td>
        </tr>
        <tr>
            <td>Contains Mature Content:</td>
            <td>{{panel.mature_content|yesno:"Yes,No"}}</td>
        </tr>
        <tr>
            <td>Panel Day:</td>
            <td>
                <ul class="px-0">
                    {% for day in panel.panel_day.all %}
                    <li>{{day.name}}</li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
        <tr>
            <td>Panel Times:</td>
            <td>
                <ul class="px-0">
                    {% for time in panel.panel_times.all %}
                    <li>{{time.name}}</li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
        <tr>
            <td>Agrees to check ID's:</td>
            <td>{{panel.check_ids|yesno:"Yes,No"}}</td>
        </tr>
        <tr>
            <td>State:</td>
            <td>{{panel.get_panel_state_display}} ({{panel.state_changed}})</td>
        </tr>
        {% if panel.panel_state == "STATE_ASSIGNED" %}
        <tr>
            <td>Panel Schedule:</td>
            <td>
                {{panel.scheduled_room}} - {{panel.scheduled_day}}@{{panel.scheduled_time|time:'h:i A'}}
            </td>
        </tr>
        {% endif %}
    </table>
</div>
<div>
    <h2>Actions</h2>
    {% if panel.panel_state == "STATE_NEW" %}
    <a href="{% url 'console:panel-accept' panel.id %}" class="btn btn-primary">Accept</a>
    <a href="{% url 'console:panel-waitlist' panel.id %}" class="btn btn-primary">Waitlist</a>
    <a href="{% url 'console:panel-deny' panel.id %}" class="btn btn-primary">Deny</a>
    {% elif panel.panel_state == "STATE_WAITLISTED" %}
    <a href="{% url 'console:panel-accept' panel.id %}" class="btn btn-primary">Accept</a>
    <a href="{% url 'console:panel-deny' panel.id %}" class="btn btn-primary">Deny</a>
    {% elif panel.panel_state == "STATE_ACCEPTED" %}
    <a href="{% url 'console:panel-assign' panel.id %}" class="btn btn-primary">Schedule</a>
    {% elif panel.panel_state == "STATE_ASSIGNED" %}
    <a href="{% url 'console:panel-assign' panel.id %}" class="btn btn-primary">Re-Scehdule</a>
    <a href="{% url 'console:panel-unassign' panel.id %}" class="btn btn-secondary">Unschedule</a>
    <a href="{% url 'console:panel-cancel' panel.id %}" class="btn btn-warning">Cancel</a>
    {% endif %}
    <a href="{% url 'console:panel-delete' panel.id %}" class="btn btn-danger">Delete</a>
</div>
<div>
    <h2>Registration</h2>
    <a href="{{registration_search_base}}{{panel.email|urlencode}}" target="_blank" class="btn btn-outline-primary">{{registration_platform}} Lookup</a>
</div>
{% endblock %}

console/templates/console-performers-assign.html
{% extends 'console.html' %}
{% load crispy_forms_tags %}

{% block title %}PAWCon Apply Console - Performers{% endblock %}

{% block tool %}
<h1>Performer Schedule</h1>
<div class="col-md-6">
    <form action="{% url 'console:performer-assign' performer.id %}" method="post" class="form">
        {% crispy form %}
        <input type="submit" value="Save" class="btn btn-primary">
    </form>
</div>
{% endblock %}