dancecomp/urls.py
from django.urls import path

from . import views

app_name='dancecomp'
urlpatterns = [
    path('', views.index, name='index'),
    path('apply', views.apply, name='apply'),
    path('new', views.new, name='new'),
    path('confirm', views.confirm, name='confirm')
]

paw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('console/', include('console.urls')),
    path('merchants/', include('merchants.urls')),
    path('panels/', include('panels.urls')),
    path('performers/', include('performers.urls')),
    path('volunteers/', include('volunteers.urls')),
    path('partyfloor/', include('partyfloor.urls')),
    path('dancecomp/', include('dancecomp.urls'))
]

dancecomp/models.py
from core.models import ApplicationState, Event
from django.db import models

# Create your models her
class Competitor(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    email = models.CharField(max_length=100)
    legal_name = models.CharField(max_length=200)
    fan_name = models.CharField(max_length=200)
    competitor_name = models.CharField(max_length=200,default="")
    phone_number = models.CharField(max_length=15)
    twitter_handle = models.CharField('Twitter/BSky Handle', max_length=30)
    telegram_handle = models.CharField(max_length=30)
    music_url = models.URLField(default="", help_text="Please provide us with a link to the music for your performance. Something like a DropBox or Box link will be fine.")
    is_group = models.BooleanField('Group Performance', default=False, help_text="Check this if you are entering as a group and provide the names of the other competitors below.")
    performer_two = models.CharField(max_length=200, null=True, blank=True)
    performer_three = models.CharField(max_length=300, null=True, blank=True)
    performer_four = models.CharField(max_length=300, null=True, blank=True)
    performer_five = models.CharField(max_length=300, null=True, blank=True)
    competitor_state = models.CharField(max_length=20, null=False, choices=ApplicationState, default=ApplicationState.STATE_NEW)
    state_changed = models.DateField(auto_now_add=True)

dancecomp/forms/competitor_form.py
from core.models import get_current_event
from crispy_forms.bootstrap import InlineField, PrependedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Field, Fieldset, Layout, Submit
from django import forms

from core.models import DaysAvailable
from dancecomp.models import Competitor

class CompetitorForm(forms.ModelForm):
    class Meta:
        model = Competitor
        fields = (
            'email',
            'legal_name',
            'fan_name',
            'competitor_name',
            'phone_number',
            'twitter_handle',
            'telegram_handle',
            'music_url',
            'is_group',
            'performer_two',
            'performer_three',
            'performer_four',
            'performer_five'
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Fields
        self.fields['twitter_handle'].required = False
        self.fields['telegram_handle'].required = False
        self.fields['performer_two'].required = False
        self.fields['performer_three'].required = False
        self.fields['performer_four'].required = False
        self.fields['performer_five'].required = False

        # Crispy
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-sm-2 text-capitalize'
        self.helper.field_class = 'col-sm-10'
        self.helper.layout = Layout(
            Fieldset(
                'Contact Info',
                'email',
                'legal_name',
                'fan_name',
                'phone_number',
                PrependedText('twitter_handle', '@'),
                PrependedText('telegram_handle', '@'),
            ),
            Fieldset(
                'Competitor Info',
                'competitor_name',
                'music_url',
                'is_group',

            ),
            Fieldset(
                'Group Registration',
                'performer_two',
                'performer_three',
                'performer_four',
                'performer_five'
            )
        )

        self.helper.add_input(Submit('submit', 'Apply', css_class='float-end'))

dancecomp/views.py
from core.models import get_current_event
from django.conf import settings
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from modules.email import send_paw_email

from .forms import CompetitorForm
from .models import Competitor, Event

# Create your views here.
def index(request):
    event = get_current_event()
    context = {
        'is_dancecomp': True,
        'event': event
    }
    return render(request, 'dancecomp.html', context)

def apply(request):
    event = get_current_event()

    form = CompetitorForm()

    context = {
        'is_dancecomp': True,
        'event': event,
        'form': form
    }
    return render(request, 'dancecomp-apply.html', context)

def new(request):
    event = get_current_event()
    form = CompetitorForm(request.POST)
    
    if form.is_valid():
        competitor = form.save(commit=False)
        competitor.event = event
        competitor.save()

        send_paw_email('email-dance-confirm.html', {'competitor':competitor}, subject='PAWCon Dance Comp Submission', recipient_list=[competitor.email], reply_to=settings.DANCE_EMAIL)

        return HttpResponseRedirect(reverse('dancecomp:confirm'))

    for field, errors in form.errors.items():
        for error in errors:
            print(f"Form Error: {field}: {error}")

    context = {
        'is_dancecomp': True,
        'event': event,
        'form': form
    }

    return render(request, 'dancecomp-apply.html', context)

def confirm(request):
    event = get_current_event()

    context = {
        'event': event,
        'is_dancecomp': True
    }

    return render(request, 'dancecomp-confirm.html', context)

dancecomp/templates/dancecomp-apply.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}PAW Dance Comp - Application{% endblock %}

{% block content %}
<h1>Dance Comp Application</h1>
{% if event.module_competitors_enabled %}
<form action="{% url 'dancecomp:new' %}" method="post">
  {% crispy form %}
</form>
{% else %}
<div class="alert alert-danger" rolse="alert">
    Sorry Applictions for the Dance Competition are currently closed.
</div>
{% endif %}
{% endblock %}

dancecomp/templates/dancecomp-confirm.html
{% extends "base.html" %}

{% block title %}PAW Dance Comp{% endblock %}

{% block content %}
<div class="alert alert-success" role="alert">
  Thank you, your application has been submitted. We will reach out to you as a soon as possible with more information.
</div>
{% endblock %}

dancecomp/templates/dancecomp.html
{% extends "base.html" %}

{% block title %}PAW Dance Comp{% endblock %}

{% block content %}
<h1>Dance Comp Policies</h1>
<h2 class="text-uppercase">Please read this:</h2>
<ul>
  <li>Dance performances should be around 3-5 minutes.</li>
  <li>You may perform as an individual or as a group.</li>
  <li>Please keep song selections to a PG-13 rating, as this is a family-friendly convention.</li>
  <li>No excessive swearing, violence, or sexual references.</li>
  <li>Songs must be submitted via Dropbox before the convention. A link will be provided to all applicants once the sign-up period ends.</li>
  <li><b>NOTE:</b> You agree to use the same email and fan name to register for the
      event when you apply to be compete. Not doing so may mean that we can
      not approve your application.</li>
  <li>By applying you agree that you understand all of the above.</li>
</ul>

{% if event.is_submissions_closed == False and event.module_competitors_enabled %}
<a href="{% url 'dancecomp:apply' %}" class="btn btn-primary btn-lg">Apply</a>
{% endif %}

{% endblock %}