core/urls.py
from django.urls import path

from . import views

app_name='core'
urlpatterns = [
    path('', views.index, name='index'),
]

dancecomp/urls.py
from django.urls import path

from . import views

app_name='dancecomp'
urlpatterns = [
    path('', views.index, name='index'),
    path('apply', views.apply, name='apply'),
    path('new', views.new, name='new'),
    path('confirm', views.confirm, name='confirm')
]

merchants/urls.py
from django.urls import path

from . import views

app_name='merchants'
urlpatterns = [
    path('', views.index, name='index'),
    path('apply', views.apply, name='apply'),
    path('new', views.new, name='new'),
    path('confirm', views.confirm, name='confirm')
]

panels/urls.py
from django.urls import path

from . import views

app_name='panels'
urlpatterns = [
    path('', views.index, name='index'),
    path('apply', views.apply, name='apply'),
    path('new', views.new, name='new'),
    path('confirm', views.confirm, name='confirm')
]

partyfloor/urls.py
from django.urls import path

from . import views

app_name='partyfloor'
urlpatterns = [
    path('', views.index, name='index'),
    path('apply', views.apply, name='apply'),
    path('new', views.new, name='new'),
    path('confirm', views.confirm, name='confirm')
]

paw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('console/', include('console.urls')),
    path('merchants/', include('merchants.urls')),
    path('panels/', include('panels.urls')),
    path('performers/', include('performers.urls')),
    path('volunteers/', include('volunteers.urls')),
    path('partyfloor/', include('partyfloor.urls')),
    path('dancecomp/', include('dancecomp.urls'))
]

core/models.py
import datetime
from django.db import models

def get_current_event():
    return Event.objects.filter(event_end__gte=datetime.date.today()).order_by('event_end').first()

# Create your models here.
class ApplicationState(models.TextChoices):
    STATE_NEW = "STATE_NEW", "New"
    STATE_ACCEPTED = "STATE_ACCEPTED", "Accepted"
    STATE_ASSIGNED = "STATE_ASSIGNED", "Assigned"
    STATE_CANCELED = "STATE_CANCELED", "Canceled"
    STATE_WAITLIST = "STATE_WAITLIST", "Waitlisted"
    STATE_DENIED = "STATE_DENIED", "Denied"
    STATE_DELETED = "STATE_DELETED", "Deleted"
    STATE_OLD = "STATE_OLD", "Migrated Data"

class RoomType(models.TextChoices):
    ROOM_PANELS = "ROOM_PANELS", "Panel Space"

class DaysAvailable(models.Model):
    key = models.CharField(max_length=4, primary_key=True)
    name = models.CharField(max_length=50)
    order = models.IntegerField(default=0)
    available_scheduling = models.BooleanField(default=False)
    available_party = models.BooleanField(default=False)
    party_only = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Department(models.Model):
    department_name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    order = models.IntegerField(default=0)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.department_name

class Event(models.Model):
    event_name = models.CharField(max_length=200)
    event_start = models.DateField()
    event_end = models.DateField()
    max_merchants = models.IntegerField(default=0)
    max_party_rooms = models.IntegerField(default=0)
    submissions_end = models.DateField()
    module_panels_enabled = models.BooleanField(default=False)
    module_merchants_enabled = models.BooleanField(default=False)
    module_performers_enabled = models.BooleanField(default=False)
    module_partyfloor_enabled = models.BooleanField(default=False)
    module_competitors_enabled = models.BooleanField(default=False)
    voucher_performers = models.CharField(max_length=20, default="")
    voucher_volunteer = models.CharField(max_length=20, default="")

    def is_submissions_closed(self):
        return self.submissions_end < datetime.date.today()

    def __str__(self):
        return self.event_name

class SchedulingConfig(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    day_available = models.ForeignKey(DaysAvailable, on_delete=models.CASCADE)
    panels_start = models.DateTimeField()
    panels_end = models.DateTimeField()
    performers_start = models.DateTimeField()
    performers_end = models.DateTimeField()

class EventRoom(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    room_name = models.CharField(max_length=100)
    room_type = models.CharField(max_length=20, choices=RoomType, default=RoomType.ROOM_PANELS)


    def __str__(self):
        return self.room_name
    

core/views.py
from core.models import get_current_event
from django.shortcuts import render

from .models import Event

# Create your views here.
def index(request):
    event = get_current_event()
    context = {
        'is_home': True,
        'event': event
    }
    return render(request, 'home.html', context)

core/templates/home.html
{% extends "base.html" %}

{% block title %}PAW Apply{% endblock %}

{% block content %}
<h1>Welcome! I would like to...</h1>
<div class="row">
    {% if event.is_submissions_closed %}
    <div class="col-sm-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Volunteer</h5>
                <p class="card-text">Volunteers are key to PAW's success if you wish to help be part of that. Apply to
                    volunteer with us.</p>
                <a href="{% url 'volunteers:index' %}" class="btn btn-primary">Volunteer</a>
            </div>
        </div>
    </div>
    {% else %}
    <div class="col-sm-4 d-flex align-items-stretch">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Volunteer</h5>
                <p class="card-text">Volunteers are key to PAW's success if you wish to help be part of that. Apply to
                    volunteer with us.</p>
                <a href="{% url 'volunteers:index' %}" class="btn btn-primary">Volunteer</a>
            </div>
        </div>
    </div>
    {% if event.module_panels_enabled %}
    <div class="col-sm-4 d-flex align-items-stretch">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Host A Panel</h5>
                <p class="card-text">Panels are an important part of PAW's success. Panels allow us to educate,
                    entertain and interact with our community.</p>
                <a href="{% url 'panels:index' %}" class="btn btn-primary">Submit</a>
            </div>
        </div>
    </div>
    {% endif %}
    {% if event.module_merchants_enabled %}
    <div class="col-sm-4 d-flex align-items-stretch">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Become a Merchant</h5>
                <p class="card-text">Our vibrant shopping district attracts merchants of all types, allowing them to
                    share their wares with our attendees.</p>
                <a href="{% url 'merchants:index' %}" class="btn btn-primary">Apply</a>
            </div>
        </div>
    </div>
    {% endif %}
</div>
<div class="row mt-4">
    {% if event.module_performers_enabled %}
    <div class="col-sm-4 d-flex align-items-stretch">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Perform</h5>
                <p class="card-text">DJ's are a critical element of con nightlife. Submit your demo for a chance to play
                    on stage and showcase your unique sound!</p>
                <a href="{% url 'performers:index' %}" class="btn btn-primary">Apply</a>
            </div>
        </div>
    </div>
    {% endif %}
    {% if event.module_partyfloor_enabled %}
    <div class="col-sm-4 d-flex align-items-stretch">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Throw a Party</h5>
                <p class="card-text">Strut your stuff on the PAWCon party floor! Want to host a party? Or just be right
                    in the middle of the action?</p>
                <a href="{% url 'partyfloor:index' %}" class="btn btn-primary">Party!</a>
            </div>
        </div>
    </div>
    {% endif %}
    {% if event.module_competitors_enabled %}
    <div class="col-sm-4 d-flex align-items-stretch">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Compete</h5>
                <p class="card-text">No better way to show us your moves than by competing in our Dance Competition for
                    free con membership and other prizes!</p>
                <a href="{% url 'dancecomp:index' %}" class="btn btn-primary">Enter</a>
            </div>
        </div>
    </div>
    {% endif %}
    {% endif %}
</div>
{% endblock %}