console/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name='console'
urlpatterns = [
    path('', views.ConsoleIndexPageView.as_view(), name='index'),
    path('login', views.ConsoleLoginPageView.as_view(), name='login'),
    path('logout', views.ConsoleLogoutRedirect.as_view(), name='logout'),
    path('forgot-password', views.ResetPasswordView.as_view(), name='forgot-password'),
    path('forgot-password-confirm/<uidb64>/<token>', views.ResetPasswordConfirmView.as_view(), name='forgot-password-confirm'),
    path('forgcot-password-complete', views.ResetPasswordCompleteView.as_view(), name='forgot-password-complete'),


    # Merchants
    path('merchants', views.MerchantsListPageView.as_view(), name='merchants'),
    path('merchants/download_csv', views.MerchantCSVDownloadView.as_view(), name='merchant-download'),
    path('merchants/<int:merchant_id>', views.MerchantDetailsPageView.as_view(), name='merchant-detail'),
    path('merchants/<int:merchant_id>/accept', views.MerchantActionAcceptedRedirect.as_view(), name='merchant-accept'),
    path('merchants/<int:merchant_id>/payment', views.MerchantActionRequestPaymentRedirect.as_view(),  name='merchant-payment'),
    path('merchants/<int:merchant_id>/confirm', views.MerchantActionPaymentConfirmedRedirect.as_view(), name='merchant-confirm'),
    path('merchants/<int:merchant_id>/register', views.MerchantActionRegistrationReminderRedirect.as_view(), name='merchant-reg-remind'),
    path('merchants/<int:merchant_id>/waitlist', views.MerchantActionWaitlistRedirect.as_view(), name='merchant-waitlist'),
    path('merchants/<int:merchant_id>/delete', views.MerchantActionDeleteRedirect.as_view(), name='merchant-delete'),
    path('merchants/<int:merchant_id>/assign', views.MerchantActionAssignPageView.as_view(), name='merchant-assign'),

    # Panels
    path('panels', views.PanelsListPageView.as_view(), name='panels'),
    path('panels/<int:panel_id>', views.PanelDetailsPageView.as_view(), name='panel-detail'),
    path('panels/<int:panel_id>/accept', views.PanelActionAcceptRedirect.as_view(), name='panel-accept'),
    path('panels/<int:panel_id>/waitlist', views.PanelActionWaitlistRedirect.as_view(), name='panel-waitlist'),
    path('panels/<int:panel_id>/deny', views.PanelActionDenyRedirect.as_view(), name='panel-deny'),
    path('panels/<int:panel_id>/delete', views.PanelActionDeleteRedirect.as_view(), name='panel-delete'),
    path('panels/schedule', views.PanelSchedulePageView.as_view(), name='panels-schedule'),
    path('panels/schedule/<int:panel_id>/assign', views.PanelActionAssignPageView.as_view(), name='panel-assign'),
    path('panels/schedule/<int:panel_id>/unassign', views.PanelActionUnscheduleRedirect.as_view(), name='panel-unassign'),
    path('panels/schedule/<int:panel_id>/cancel', views.PanelActionCancelRedirect.as_view(), name='panel-cancel'),

    # Volunteers
    path('volunteers', views.VolunteerListPageView.as_view(), name='volunteers'),
    path('volunteers/download_csv', views.VolunteerCSVDownloadView.as_view(), name='volunteer-download'),
    path('volunteers/<int:volunteer_id>', views.VolunteerDetailsPageView.as_view(), name='volunteer-detail'),
    path('volunteers/<int:volunteer_id>/accept', views.VolunteerActionAcceptRedirect.as_view(), name='volunteer-accept'),
    path('volunteers/<int:volunteer_id>/decline', views.VolunteerActionDeclinedRedirect.as_view(), name='volunteer-decline'),
    path('volunteers/<int:volunteer_id>/delete', views.VolunteerActionDeleteRedirect.as_view(), name='volunteer-delete'),
    path('volunteers/<int:volunteer_id>/task', views.VolunteerAddTaskPageView.as_view(), name='volunteer-add-task'),
    path('volunteers/<int:volunteer_id>/task/<int:task_id>/edit', views.VolunteerEditTaskPageView.as_view(), name="volunteer-edit-task"),
    path('volunteers/<int:volunteer_id>/task/<int:task_id>/delete', views.VolunteerActionDeleteTaskRedirect.as_view(), name="volunteer-delete-task"),
    path('volunteers/dashboard', views.VolunteerDashboardPageView.as_view(), name="volunteer-dashboard"),
    path('volunteers/dashboard/task/<int:volunteer_id>/start', views.VolunteerStartTaskRedirect.as_view(), name='volunteer-task-start'),
    path('volunteers/dashboard/task/<int:task_id>/end', views.VolunteerEndTaskRedirect.as_view(), name='volunteer-task-end'),
    path('volunteers/email', views.VolunteerComposeMassEmailPageView.as_view(), name='volunteer-email'),

    # Performers
    path('performers', views.PerformersListPageView.as_view(), name='performers'),
    path('performers/<int:performer_id>', views.PerformerDetailPageView.as_view(), name='performer-detail'),
    path('performers/<int:performer_id>/accept', views.PerformerActionAcceptRedirect.as_view(), name='performer-accept'),
    path('performers/<int:performer_id>/waitlist', views.PerformerActionWaitlistRedirect.as_view(), name='performer-waitlist'),
    path('performers/<int:performer_id>/decline', views.PerformerActionDeclineRedirect.as_view(), name='performer-decline'),
    path('performers/<int:performer_id>/delete', views.PerformerActionDeleteRedirect.as_view(), name='performer-delete'),
    path('performers/schedule', views.PerformersSchedulePageView.as_view(), name='performer-schedule'),
    path('performers/schedule/<int:performer_id>/assign', views.PerformerActionAssignPageView.as_view(), name='performer-assign'),
    path('performers/schedule/<int:performer_id>/unassign', views.PerformerActionUnscheduleRedirect.as_view(), name='performer-unassign'),

    # Party Hosts
    path('hosts', views.PartyHostListPageViewView.as_view(), name='hosts'),
    path('hosts/<int:host_id>', views.PartyHostDetailPageView.as_view(), name='host-detail'),
    path('hosts/<int:host_id>/accept', views.PartyHostActionAcceptRedirect.as_view(), name='host-accept'),
    path('hosts/<int:host_id>/assign', views.PartyHostActionAssignPageView.as_view(), name='host-assign'),
    path('hosts/<int:host_id>/waitlist', views.PartyHostActionWaitlistRedirect.as_view(), name='host-waitlist'),
    path('hosts/<int:host_id>/decline', views.PartyHostActionDeclineRedirect.as_view(), name='host-decline'),
    path('hosts/<int:host_id>/delete', views.PartyHostActionDeleteRedirect.as_view(), name='host-delete'),

    # Competitors
    path('competitors', views.CompetitorsListPageView.as_view(), name='competitors'),
    path('competitors/<int:competitor_id>', views.CompetitorDetailPageView.as_view(), name='competitor-detail'),
    path('competitors/<int:competitor_id>/accept', views.CompetitorActionAcceptRedirect.as_view(), name='competitor-accept'),
    path('competitors/<int:competitor_id>/decline', views.CompetitorActionDeclineRedirect.as_view(), name='competitor-decline'),
    path('competitors/<int:competitor_id>/delete', views.CompetitorActionDeleteRedirect.as_view(), name='competitor-delete')
]

paw/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('console/', include('console.urls')),
    path('merchants/', include('merchants.urls')),
    path('panels/', include('panels.urls')),
    path('performers/', include('performers.urls')),
    path('volunteers/', include('volunteers.urls')),
    path('partyfloor/', include('partyfloor.urls')),
    path('dancecomp/', include('dancecomp.urls'))
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}PAWCon Apply{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">

    <style>
        body {
            padding-top: 5rem;
            padding-bottom: 5rem;
        }

        .bg-purple {
            background-color: #6f42c1;
        }
    </style>
    <!-- Custom styles for this template -->
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-purple fixed-top">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbar">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link {{ is_home|yesno:" active," }}" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ is_volunteers|yesno:" active," }}" href="/volunteers">Volunteers</a>
                    </li>
                    {% if event.module_panels_enabled %}
                    <li class="nav-item">
                        <a class="nav-link {{ is_panels|yesno:" active," }}" href="/panels">Panels</a>
                    </li>
                    {% endif %}
                    {% if event.module_merchants_enabled %}
                    <li class="nav-item">
                        <a class="nav-link {{ is_merchants|yesno:" active," }}" href="/merchants">Merchants</a>
                    </li>
                    {% endif %}
                    {% if event.module_performers_enabled %}
                    <li class="nav-item">
                        <a class="nav-link {{ is_djs|yesno:" active," }}" href="/performers">DJs</a>
                    </li>
                    {% endif %}
                    {% if event.module_partyfloor_enabled %}
                    <li class="nav-item">
                        <a class="nav-link {{ is_partyfloor|yesno:" active," }}" href="/partyfloor">Party Floor</a>
                    </li>
                    {% endif %}
                    {% if event.module_competitors_enabled %}
                    <li class="nav-item">
                        <a class="nav-link {{ is_dancecomp|yesno:"active," }}" href="/dancecomp">Dance Comp</a>
                    </li>
                    {% endif %}
                    {% if request.user.id != None %}
                    <li class="nav-item">
                        <a class="nav-link {{ is_console|yesno:" active,"}}" href="/console">Console</a>
                    </li>
                    {% endif %}
                </ul>
                {% if request.user.id != None %}
                <span class="navbar-text float-end">
                    <a href="/console/logout" class="nav-link"><span class="bi-person-circle"></span>
                        {{request.user.username}}</a>
                </span>
                {% endif %}
            </div>
        </div>
    </nav>

    <main role="main" class="container">
        {% block content %}{% endblock %}
    </main><!-- /.container -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
</body>

</html>

templates/console-base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}PAWCon Apply Console{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <script src="https://kit.fontawesome.com/3a6ea9b9db.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/easymde@2.18.0/dist/easymde.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/easymde@2.18.0/dist/easymde.min.js"></script>
    
    <style>
        body {
            padding-top: 5rem;
        }

        .bg-purple {
            background-color: #6f42c1;
        }
    </style>
    <!-- Custom styles for this template -->
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-purple fixed-top">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbar">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link {{ is_home|yesno:" active," }}" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {{ is_volunteers|yesno:" active," }}" href="/volunteers">Volunteers</a>
                    </li>
                    {% if event.module_panels_enabled %}
                    <li class="nav-item">
                        <a class="nav-link {{ is_panels|yesno:" active," }}" href="/panels">Panels</a>
                    </li>
                    {% endif %}
                    {% if event.module_merchants_enabled %}
                    <li class="nav-item">
                        <a class="nav-link {{ is_merchants|yesno:" active," }}" href="/merchants">Merchants</a>
                    </li>
                    {% endif %}
                    {% if event.module_performers_enabled %}
                    <li class="nav-item">
                        <a class="nav-link {{ is_djs|yesno:" active," }}" href="/performers">DJs</a>
                    </li>
                    {% endif %}
                    {% if event.module_partyfloor_enabled %}
                    <li class="nav-item">
                        <a class="nav-link {{ is_partyfloor|yesno:" active," }}" href="/partyfloor">Party Floor</a>
                    </li>
                    {% endif %}
                    {% if event.module_competitors_enabled %}
                    <li class="nav-item">
                        <a class="nav-link {{ is_dancecomp|yesno:" active," }}" href="/dancecomp">Dance Comp</a>
                    </li>
                    {% endif %}
                    {% if request.user.id != None %}
                    <li class="nav-item">
                        <a class="nav-link {{ is_console|yesno:" active,"}}" href="/console">Console</a>
                    </li>
                    {% endif %}
                </ul>
                {% if request.user.id != None %}
                <span class="navbar-text float-end">
                    <a href="/console/logout" class="nav-link"><span class="bi-person-circle"></span>
                        {{request.user.username}}</a>
                </span>
                {% endif %}
            </div>
        </div>
    </nav>

    <main role="main" class="container-fluid">
        {% block content %}{% endblock %}
    </main><!-- /.container -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script>
        $(function () {
            console.log('Initializing Toasts!');
            $('.toast').toast({
                'delay': 1000
            });
        });
    </script>
    <script>
        $(function () {
            {% block javascript %}
            {% endblock %}
        });
    </script>
</body>
</html>

templates/console-email-reset-password.html
<!DOCTYPE html>
<html lang="en">
<body>
    <p>Hello {{ user.email }}</p>
    <p>A request has been received to change the password for your PAWApply account.</p>
    <p><a href="{{ protocol }}://{{ domain }}{% url 'console:forgot-password-confirm' uidb64=uid token=token %}">Reset Password</a></p>
    <p>If you did not initiate this request, please contact us immediately at laveur@pacanthro.org.</p>
    <p>Thank you,</p>
    <p>Laveur</p>
</body>
</html>

templates/email-performers-confirm.html
<!DOCTYPE html>
<html lang="en">
<body>
  <h1>Thank You!</h1>
  <b>Greetings {{performer.fan_name}} ({{performer.legal_name}}),</b>
  <p>Thank you for submitting your demo to DJ at {{peformer.event.event_name}}.</p>
  <p>We will evaluate all submitted demos once the sign-up period ends and you will receive a follow-up email if you have been formally accepted.</p>
  <b>Information you submitted:</b>
  <p>Email: {{performer.email}}</p>
  <p>Phone Number: {{performer.phone_number}}</p>
  <p>Twitter: {{performer.twitter_handle}}</p>
  <p>Telegram: {{performer.telegram_handle}}</p>
  <p>DJ Biography:</p>
  <p>{{performer.biography}}</p>
  <p>Set URL: {{performer.set_url}}</p>
  <p>Sincerely,</p>
  <p>PAWCon Programming</p>
</body>
</html>